/*
 * This Java source file was generated by the Gradle 'init' task.
 */
 
package JoshA;

import org.slf4j.Logger; 
import org.slf4j.LoggerFactory; 
import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.ApplicationArguments; 
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;


@SpringBootApplication 
public class Demo extends SpringBootServletInitializer{
    
    public static void main(String[] args){
        
        Logger logger = LoggerFactory.getLogger(Demo.class); 
        
        logger.info("this is an info message"); 
        
        logger.warn("this is a warn message"); 
        
        logger.error("this is an error message"); 
        
        SpringApplication.run(Demo.class, args); 
        
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){   
         
         return application.sources(Demo.class);
     }
}

